# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install MAUI
      run: dotnet workload install maui
    - name: Decrypt Pfx
      run: |
        echo "${{ secrets.PDFSPLITTER_PFX_CERT }}" > cert.pfx.asc
        certutil -decode cert.pfx.asc cert.pfx
    - name: Install Certificate
      run: certutil -user -q -p ${{ secrets.PDFSPLITTER_PWD }} -importpfx cert.pfx NoRoot
    - name: Build
      run: dotnet publish PdfSplitter/PdfSplitter.csproj -c Release -f:net7.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{ secrets.PDFSPLITTER_THUMB }}"    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:  
        path: /PdfSplitter/bin/Release/**/*.msix
